# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kolesa_pb2 as kolesa__pb2


class KolesaScraperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadKolesaLinks = channel.unary_unary(
                '/KolesaScraper/LoadKolesaLinks',
                request_serializer=kolesa__pb2.PhoneRequest.SerializeToString,
                response_deserializer=kolesa__pb2.LinksReply.FromString,
                )
        self.LoadKrishaLinks = channel.unary_unary(
                '/KolesaScraper/LoadKrishaLinks',
                request_serializer=kolesa__pb2.PhoneRequest.SerializeToString,
                response_deserializer=kolesa__pb2.LinksReply.FromString,
                )
        self.LoadMarketLinks = channel.unary_unary(
                '/KolesaScraper/LoadMarketLinks',
                request_serializer=kolesa__pb2.PhoneRequest.SerializeToString,
                response_deserializer=kolesa__pb2.LinksReply.FromString,
                )
        self.LoadVirusLinks = channel.unary_unary(
                '/KolesaScraper/LoadVirusLinks',
                request_serializer=kolesa__pb2.PhoneRequest.SerializeToString,
                response_deserializer=kolesa__pb2.LinksReply.FromString,
                )


class KolesaScraperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadKolesaLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadKrishaLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadMarketLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadVirusLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KolesaScraperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadKolesaLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadKolesaLinks,
                    request_deserializer=kolesa__pb2.PhoneRequest.FromString,
                    response_serializer=kolesa__pb2.LinksReply.SerializeToString,
            ),
            'LoadKrishaLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadKrishaLinks,
                    request_deserializer=kolesa__pb2.PhoneRequest.FromString,
                    response_serializer=kolesa__pb2.LinksReply.SerializeToString,
            ),
            'LoadMarketLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadMarketLinks,
                    request_deserializer=kolesa__pb2.PhoneRequest.FromString,
                    response_serializer=kolesa__pb2.LinksReply.SerializeToString,
            ),
            'LoadVirusLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadVirusLinks,
                    request_deserializer=kolesa__pb2.PhoneRequest.FromString,
                    response_serializer=kolesa__pb2.LinksReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KolesaScraper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KolesaScraper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadKolesaLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KolesaScraper/LoadKolesaLinks',
            kolesa__pb2.PhoneRequest.SerializeToString,
            kolesa__pb2.LinksReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadKrishaLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KolesaScraper/LoadKrishaLinks',
            kolesa__pb2.PhoneRequest.SerializeToString,
            kolesa__pb2.LinksReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadMarketLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KolesaScraper/LoadMarketLinks',
            kolesa__pb2.PhoneRequest.SerializeToString,
            kolesa__pb2.LinksReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadVirusLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KolesaScraper/LoadVirusLinks',
            kolesa__pb2.PhoneRequest.SerializeToString,
            kolesa__pb2.LinksReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
